### PR TITLE
Update omim_exclusions.tsv

### PR DESCRIPTION
**Pull request by sabrinatoro**
Added new term to the OMIM exclusion list

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Comment by twhetzel** [comment]
lgtm

@sabrinatoro @matentzn since these are gene symbols, is this something we want to scan and update automatically, ie to find and exclude genes?

**Comment by matentzn** [comment]
> @sabrinatoro @matentzn since these are gene symbols, is this something we want to scan and update automatically, ie to find and exclude genes?

Good idea, would be easy enough. Could make issue.

**Comment by sabrinatoro** [comment]
>since these are gene symbols, is this something we want to scan and update automatically, ie to find and exclude genes?
>Good idea, would be easy enough. Could make issue.

I don't know what OMIM file we ingest, but OMIM file indicates what entry corresponds to a gene. I thought we were already doing this (?)

**Comment by twhetzel** [comment]
Good to know, I'll make a ticket to check where and why that did not work in this round. @sabrinatoro I am assuming based on the entries in `src/ontology/config/omim_exclusions.tsv` that you added these manually, is that correct?

**Comment by sabrinatoro** [comment]
yes, I added the genes manually here, which suggests that we might not be doing what I mentioned above.

**Comment by sabrinatoro** [comment]
can we merge this PR?

**Comment by twhetzel** [comment]
PR - yeah, that's fine with me... I haven't sync'd up with @matentzn as to that process in this repo but will merge now.

**Pull request merged**
