### PR TITLE
update omim-exclusion.tsv

### PR DESCRIPTION
**Pull request by sabrinatoro**
Addresses #85

### CODE REVIEW

**Comment by sabrinatoro** [comment]
I created a new PR just to make sure I did the right thing. However the same very big difference is shown.
Even though only the first 212 lines were changed, the diff shows that ALL the lines with genes (which is the rest of the file) were deleted and re-added.
I don't know why it does this.

**Comment by sabrinatoro** [comment]
@matentzn and @joeflack4 please see THIS PR instead of the other.

**Comment by sabrinatoro** [comment]
I am adding "false" to all the lines. Please wait before reviewing
(and sorry for all the extra steps!)

**Comment by sabrinatoro** [comment]
@matentzn and @joeflack4 : this is ready for your review. Thank you!

**Review by matentzn — APPROVED** [review]
Looks great!

**Pull request merged**
