### PR TITLE
Delete duplicate variable declaration

### PR DESCRIPTION
**Pull request by joeflack4**
## Overview
Delete duplicate variable declaration in make goal

@matentzn [wrote](https://monarchinitiative.slack.com/archives/C03AW548J8M/p1732615444597049?thread_ts=1732581201.039059&cid=C03AW548J8M):
> Neither mondo.Makefile or Makefile contains the COMP variable, so the second MIR could just be deleted and merged without review and without running QC

@matentzn I could probably just merge this without review but I'm not sure!

### Documentation
Was the documentation added/updated under `docs/`?
- [ ] Yes
- [x] No, updates to the docs were not necessary after careful consideration

### QC
Was the full pipeline run before submitting this PR using `sh run.sh make build-mondo-ingest` on this branch (after 
`docker pull obolibrary/odkfull:dev`), and no errors occurred?
- [ ] Yes
- [x] No, there are no functional (code-related) changes to the pipeline in the PR, so no re-run is necessary
   
### New Packages
Were any new *Python packages* added?
- [ ] Yes, [requirements.txt.full](https://github.com/INCATools/ontology-development-kit/blob/master/requirements.txt.full) was updated and an [ODK issue](https://github.com/INCATools/ontology-development-kit/issues/new) submitted
- [x] No

Were any other *non-Python packages* added?
- [ ] Yes, [Dockerfile](https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile) updated and an [ODK issue](https://github.com/INCATools/ontology-development-kit/issues/new) submitted
- [x] No

### PR Review and Conversations Resolved
Has the PR been sufficiently reviewed by at least 1 team member of the Mondo Technical team and all threads resolved?
- [ ] Yes

### CODE REVIEW

**Review by twhetzel — APPROVED** [review]
looks ok and can be merged into `main`

**Comment by joeflack4** [comment]
Oops I meant to make this on develop not main. I also tend to do merging of my own prs. But looks like it's ok

**Comment by twhetzel** [comment]
Ah, I thought you were doing what Nico suggested (but overall we should get back to the SOP) and decided to merge into `main`. Should that merge be reverted and then merge this PR into `develop` instead, ie do you want this change in `develop` so you can merge it into any feature branch?

**Comment by matentzn** [comment]
This PR is zero risk - it's fine as is! It may touch the code but it only
Removes a duplicate value.

**Comment by twhetzel** [comment]
Yes, that is why I went ahead and merged into `main` and was just asking in case anyone did want it rolled back :)

**Pull request merged**
