### PR TITLE
Remove GARD

### LINKED ISSUE #399: Remove GARD
## Overview
This is causing errors when Joe runs `build-mondo-ingest`. There are several places ot remove.

Joe has many more notes in Workflowy.

### PR DESCRIPTION
**Pull request by joeflack4**
Resolves #399

## Overview
Removes semblance of GARD as a normal source. It's moving to EMC.

### Documentation
Was the documentation added/updated under `docs/`?
- [ ] Yes
- [x] No, updates to the docs were not necessary after careful consideration

### QC
Was the full pipeline run before submitting this PR using `sh run.sh make build-mondo-ingest` on this branch (after 
`docker pull obolibrary/odkfull:dev`), and no errors occurred?
- [x] Yes
- [ ] No, there are no functional (code-related) changes to the pipeline in the PR, so no re-run is necessary

Build PR:
- #682

### New Packages
Were any new *Python packages* added?
- [ ] Yes, [requirements.txt.full](https://github.com/INCATools/ontology-development-kit/blob/master/requirements.txt.full) was updated and an [ODK issue](https://github.com/INCATools/ontology-development-kit/issues/new) submitted
- [x] No

Were any other *non-Python packages* added?
- [ ] Yes, [Dockerfile](https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile) updated and an [ODK issue](https://github.com/INCATools/ontology-development-kit/issues/new) submitted
- [x] No

### PR Review and Conversations Resolved
Has the PR been sufficiently reviewed by at least 1 team member of the Mondo Technical team and all threads resolved?
- [ ] Yes

## Changes
Remove GARD
Remove GARD as non-EMC source
- ODK setup: metadata/gard.yml & mondo-ingest-odk.yaml
- Specific files: docs, outputs, and intermediaries.
- Refs within files: mondo-ingest.Makefile, gitignore, mkdocs.yml, Makefile (after running update_repo)

### CODE REVIEW

**Comment by joeflack4** [comment]
@matentzn Trish and I can review this. I just added you just in case you have any plans for anything I deleted, a need for these or anything else, in EMC:
- `mappings/gard.sssom.tsv`
- `config/gard_exclusions.tsv`

**Review by twhetzel — COMMENTED** [review]
Generally handling GARD has moved to EMC and is currently in the https://github.com/monarch-initiative/mondo-ingest/blob/externalclingenmedgenefo branch. NOTE: this is the active branch used by the mondo repo. The picture of how mondo-ingest and mondo interact with respect to EMC content is a bit unclear. Given that, it may be safer to get the `externalclingenmedgenefo` branch merged with the needed relevant updates to the mondo repo before merging this.

I also do not know if these files are needed:
- mappings/gard.sssom.tsv
- config/gard_exclusions.tsv

**Comment by matentzn** [comment]
> I also do not know if these files are needed:

> mappings/gard.sssom.tsv
> config/gard_exclusions.tsv

Not needed anymore!

**Comment by joeflack4** [comment]
Same, I don't see any interaction, but I don't think there's any rush.

**Comment by twhetzel** [comment]
Ok, let's sort out what's needed and make sure we all understand what's happening with the connections in the `externalclingenmedgenefo` branch first and then re-visit this.

**Comment by twhetzel** [comment]
@joeflack4 now that the EMC pipeline is sorted out, the general changes to remove the unused GARD code can be done. You will need to check if this PR is still relevant given all the changes that were needed to get the other pipelines in place for the Mondo December release.

**Comment by joeflack4** [comment]
@twhetzel I took care of the merge conflicts and re-reviewed. LGTM.

You mentioned "now that things have changed", this should be looked at. I am assuming you mean that when Nico said [these files were no longer needed](https://github.com/monarch-initiative/mondo-ingest/pull/681#issuecomment-2437112798) for EMC, that may have been true at the time, but perhaps the EMC had changed since, and that I should check to make sure that these files are indeed still not needed anywhere.

I did just do another check. I searched for these two files to see if there were any static references to them anywhere in the codebase, and there aren't any. So I think this is still looking good and ready to merge.

If you want to be absolutely sure that there is no sort of dynamic reference being made to these files, I can look deeper, or we can have Nico take another look, but I think it is probably safe to merge.

**Review by twhetzel — APPROVED** [review]
lgtm

**Comment by joeflack4** [comment]
RE: "now that things have changed", paraphrasing this:
> You will need to check if this PR is still relevant given all the changes that were needed to get the other pipelines in place for the Mondo December release.

I will merge now, thanks!

**Pull request merged**
